### ISSUE TITLE
회원가입시 이메일 아이디 통합 필요

### ISSUE THREAD

**Issue by kohbwoo** [Air-Alarm/Air-Alarm-IOS#23]
<img width="494" alt="스크린샷 2021-09-27 오전 4 11 14" src="https://user-images.githubusercontent.com/29862835/134821055-2815ca53-672b-4247-bd22-da1592b2b42d.png">
ID 항목은 삭제
사진상 첫번째 칸이 이메일이 되도록

**Comment by hanni66** [comment]
통합 완료
